### PR TITLE
Login and Loading Early Exits

### LINKED ISSUE #90: Catch error for user login when unable to reach backend
Current error:

image

We should handle the promise and show an error message to regain connection before trying agian

### PR DESCRIPTION
**Pull request by julianrkung**
[//]: # "These comments are meant for your reference. They are invisible and don't need to be deleted!"

# What's new in this PR
This PR:
1. Disables the "login" and "create account" buttons in the login screen if the user is not online
2. Exits out of the "Loading" screen if the user is on the screen for more than 15 seconds

Temporary fix for: https://github.com/calblueprint/meepanyar/issues/90

[//]: # "Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

### Disabled Buttons
1. Run the frontend and not the backend and make sure the "Login" and "Create Account" buttons are disabled after some time

### Exit out of loading screen
1. Run the frontend and backend
2. Log in to any account, but immediately after you press "Login" and enter the "Loading" screen, stop running the backend so that the you remain stuck in the "Loading" screen
3. You should be brought back to the login page after 15 seconds in the loading screen
4. Run the backend again and log in as usual and get to the home page and make sure that after 15 seconds you aren't redirected back to the login page (it should only happen if you're stuck in the loading screen)

[//]: # 'The order in which to review files and what to expect when testing locally'

### Online sources

[//]: # 'Optional - copy links to any tutorial or documentation that was useful to you when working on this PR'

### Related PRs

[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

## Next steps

[//]: # "What's NOT in this PR, doesn't work yet, and/or still needs to be done"

### Screenshots

[//]: # "Add screenshots of expected behavior - GIFs if you're feeling fancy!"

CC: @julianrkung

[//]: # 'This tags Julian as a default. Feel free to change, or add on anyone who you should be in on the conversation.'

### CODE REVIEW

File: src/components/BaseComponents/LoadingComponent.tsx [hunk 1]
```diff
@@ -19,6 +20,17 @@ interface LoadingComponentProps {
...
 const LoadingComponent = (props: LoadingComponentProps) => {
   const { classes } = props;
+  const history = useHistory();
+
+  // If a user is stuck on the loading screen for more than 15 seconds, we send them back to the login screen
+  useEffect(() => {
+    const timeoutId = setTimeout(() => history.push('/login'), 15000)
+    return () => {
+      clearTimeout(timeoutId)
+      console.log("Timeout cleared")
```
Comment (cnnmon) [inline src/components/BaseComponents/LoadingComponent.tsx]: Do we keep in console.logs here?

**Review by cnnmon — APPROVED** [review]
Great job!

File: src/components/BaseComponents/LoadingComponent.tsx (hunk 1 above)
Comment (julianrkung) [reply src/components/BaseComponents/LoadingComponent.tsx]: Good point, i'll remove this, thanks!
